version: '3'
services:
  alex-cool-db:
    image: postgres
    volumes:
      - my-database-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=alex
      - POSTGRES_DB=alexdb
    networks:
      - my_network
  
  alex-cool-web:
    build: .
    ports:
      - 8888:8080
    environment:
      - MYDATABASECONNECTIONSTRING=Server=alex-cool-db;password=mypassword;user id=alex;database=alexdb;
    networks:
      - my_network

    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080/"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 3s


  proxy:
    image: nginx
    ports:
      - 5000:80
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      alex-cool-web:
        condition: service_healthy
    networks:
      - my_network




networks:
  my_network:


volumes:
  my-database-data: