
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: alex
  name: blazor-web-deployment
  labels:
    app: blazor-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazor-web
  template:
    metadata:
      labels:
        app: blazor-web
    spec:
      containers:
      - name: blazor-web
        image: 144.17.92.12:5000/alex/blazor-web:${GITHUB_RUN_ID}
        ports:
        - containerPort: 8080
        env:
        - name: COLLECTOR_URL 
          value: http://otel-collector-service:4317/
        - name: MYDATABASECONNECTIONSTRING
          value: Server=blazor-web-db-service;password=alex-password;user id=alex-user;database=alexdb;
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5


