name: pull request environment
on:
  pull_request:
    types: [opened, reopened]
jobs:
  deploy-to-kubernetes:
    runs-on: self-hosted
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: deploy kubernetes environment
        run: |
          export PULL_REQUEST_ID=${{ github.event.pull_request.number }}
          echo $PULL_REQUEST_ID
          export RUN_SALT="pr-${PULL_REQUEST_ID}-${GITHUB_RUN_ID}"
          export NAMESPACE="alex-pr-$PULL_REQUEST_ID"
          
          kubectl create namespace $NAMESPACE || true

          kubectl -n $NAMESPACE delete configmap blazor-web-postgres-init || true
          kubectl -n $NAMESPACE create configmap blazor-web-postgres-init --from-file=init.sql
          
          docker build -t 144.17.92.12:5000/alex/blazor-web:$RUN_SALT .
          docker push 144.17.92.12:5000/alex/blazor-web:$RUN_SALT


          for file in ./kube-pr/*; do
            echo "Applying $file"
            cat $file | envsubst | kubectl apply -f -
          done
  comment:

    runs-on: ubuntu-latest
    steps:
      - name: Comment on Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'check out the pull request at <http://${{ github.event.pull_request.number }}.alex-kube-ts.duckdns.org>'
            });